server:
  port: 8082
  servlet:
    context-path: /lendo

jwt:
  secret: lendo_project
  expiry: 900000

gorest:
  baseUrl: https://gorest.co.in
  endpoints:
    users: /public/v2/users
    posts: /public/v2/posts
    comments: /public/v2/comments
